# Generated by Django 4.2.6 on 2023-12-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.RemoveField(
            model_name='article',
            name='date_posted',
        ),
        migrations.AddField(
            model_name='article',
            name='newsapi_id',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
