# Generated by Django 4.2.6 on 2023-12-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_categories',
            field=models.ManyToManyField(blank=True, to='api.category'),
        ),
    ]
